trigger: none

schedules:
- cron: 0 0 * * *
  displayName: Daily
  branches:
    include:
      - main
  always: true

variables:
  - group: Default
  - name: operation
    value: 'Scheduled Task'
    
steps:
  - template: ../scheduled_tasks.yml
    parameters:
      tasks:
        # Collection of processes to run in this order
        - name: Remove KeyVault Policies
          script: remove-kv-policy.ps1