trigger: none

steps:
  - template: ../perform_request.yml
    parameters:
      tasks:
        # Collection of processes to run in this order
        - name: Create Resource group
          script: resource-group-create.ps1

        - name: Create Service Connection
          script: service-connection-create.ps1
          condition: eq(create_service_connection, 'true')

        - name: Update Service Connection Permissions
          arguments: -resources "$(resources)" -permission_level "Contributor" -service_connection_name "$(service_connection_name)"
          condition: eq(create_service_connection, 'true')
          script: service-connection-permissions.ps1