trigger: none

steps:
  - template: ../perform_request.yml
    parameters:
      tasks:
        # Collection of processes to run in this order
        - name: Create Service Connection
          script: service-connection-create.ps1

        - name: Update Service Connection Permissions
          arguments: -service_connection_name "$(service_connection_name)"
          script: service-connection-permissions.ps1