trigger: none

steps:
  - template: ../perform_request.yml
    parameters:
      tasks:
        # Collection of processes to run in this order
        - name: Update Service Connection Permissions
          script: service-connection-permissions.ps1